apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cau3
  name: role-readonly
rules:
- apiGroups: ["" , "apps"]
  resources: ["deployments" , "services"]
  verbs: ["get" , "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-readonly
  namespace: cau3
subjects:
- kind: ServiceAccount
  name: webapp-sa
  namespace: cau3
roleRef:
  kind: Role
  name: role-readonly
  apiGroup: rbac.authorization.k8s.io
