apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: cau3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp-sa
      containers:
      - name: webapp
        image: nginx:latest
        resources:
          requests:
            cpu: "300m"
          limits:
            cpu: "500m" 
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: cau3
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-sa
  namespace: cau3