apiVersion: v1
kind: Pod
metadata: 
  name : multi-pod
  namespace: cau2
spec:
  containers:
    - name: pod1
      image: busybox:1.31.1
      volumeMounts:
        - name : log-volume
          mountPath: /vol
      command: ["/bin/sh", "-c"]
      args: ["while true; do date >> /vol/date.log; sleep 5; done"]
    - name: pod2
      image: nginx:latest
      volumeMounts:
        - name : log-volume
          mountPath: /usr/share/nginx/html
  volumes: 
    - name: log-volume
      emptyDir: {}

